### ISSUE TITLE
Decode JWT Token (if defined) even if the route is defined as passthrough

### ISSUE THREAD

**Issue by mateuslopes** [tuupola/slim-jwt-auth#26] opened 2016-01-24 02:03 UTC
I've got this problem while developing my application...

I have a public route, defined as passthrough route in my JWT configuration, but, even that these route is a public/passthrough route, I want to register some logs and other stuff related to the user's actions in that page, if the user is already logged and passes a valid token to this opened route.

The problem is that, when routes are defined as passthrough, the defined callback function is just ignored and never triggers. So, my token is never decoded, even if I pass it by header or environment variable.

So, I think it should be good to have tokens decoded properly on passthrough routes, in such a way that it is not mandatory to have them, but, if they are there, i can have a way to handle them and, maybe, give some additional stuff to that logged user.

For now, I solved my problem making a middleware that comes just after JwtAuthentication middleware, and that tries to find the $app->jwt defined in the previous callback. If it just not find it, it means that the route is passthrough and that the callback function was not triggered... then I decode the JWT manually getting the header bearer token and using Firebase\JWT\JWT::decode() function to decode it properly.

It would be nice to have this issue implemented.

Anyway, thank you very much for this very useful lib.

**Comment by tuupola** [comment] 2016-01-25 01:49
Duplicate of #27.

**Closed by tuupola** 2016-01-25 01:49 UTC
